### PR TITLE
Only automerge for `pre-commit`/`github-actions`

### PR DESCRIPTION
**Pull request by paddyroddy**
Following on from @stefpiatek's concerns in UCL-ARC/harvest_weekly#46 this means that autoupdating will only happen for `pre-commit`/`github-actions`.

What this config will now do is:
- Only run on weekdays
- Disable the dependency dashboard
- Enable `pre-commit`
- Shorten commit titles for `github-actions` & `pre-commit` (I think the default is too long)
- Automerge via `branch` for `digest`, `minor` & `patch` updates, but only for `github-actions` & `pre-commit`

### CODE REVIEW

**Review by stefpiatek — APPROVED** [review]
Ha, the last comment I had was that we could probably leave it as-is until it becomes a problem but looks good.

**Comment by paddyroddy** [comment]
> Ha, the last comment I had was that we could probably leave it as-is until it becomes a problem but looks good.

Don't worry, I didn't do it for you. I did it because @drmatthews wanted it for MIRSG. Anyway, where is my approval?

**Comment by paddyroddy** [comment]
image
Weird

**Review by samcunliffe — APPROVED** [review]

**Comment by paddyroddy** [comment]
> Probably repo permissions. Can you try giving `maintainer` to `@collaborations`

Good spot! Added as `write`

**Pull request merged**
